package com.tepper.www;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-16T20:14:20.715+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "TaskWebserviceImplService", 
                  wsdlLocation = "http://19.16.88.82:81/webservice/taskWebService?wsdl",
                  targetNamespace = "http://www.tepper.com") 
public class TaskWebserviceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tepper.com", "TaskWebserviceImplService");
    public final static QName TaskWebserviceImplPort = new QName("http://www.tepper.com", "TaskWebserviceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://19.16.88.82:81/webservice/taskWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskWebserviceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://19.16.88.82:81/webservice/taskWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaskWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskWebserviceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TaskWebserviceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskWebserviceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TaskWebserviceImpl
     */
    @WebEndpoint(name = "TaskWebserviceImplPort")
    public TaskWebserviceImpl getTaskWebserviceImplPort() {
        return super.getPort(TaskWebserviceImplPort, TaskWebserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskWebserviceImpl
     */
    @WebEndpoint(name = "TaskWebserviceImplPort")
    public TaskWebserviceImpl getTaskWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(TaskWebserviceImplPort, TaskWebserviceImpl.class, features);
    }

}
